"""empty message

Revision ID: d3d7c20f0585
Revises: e622db06d278
Create Date: 2021-10-11 16:28:21.486300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d7c20f0585'
down_revision = 'e622db06d278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_contact_email_key', 'contact', type_='unique')
    op.drop_constraint('contact_phone_key', 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contact_phone_key', 'contact', ['phone'])
    op.create_unique_constraint('contact_contact_email_key', 'contact', ['contact_email'])
    # ### end Alembic commands ###
